name: Build and Test Docker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t tpk3d:test .

      - name: Run container and smoke-test
        run: |
          docker run -d --name tpk3d-smoke -p 8080:80 tpk3d:test
          sleep 5
          curl -f http://localhost:8080 || (docker logs tpk3d-smoke && exit 1)
          docker stop tpk3d-smoke
