name: Build and Test Docker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t tpk3d:test .
      - name: Smoke-test container
        run: |
          docker run -d --name smoke -p 8080:80 tpk3d:test
          sleep 5
          curl -f http://localhost:8080
          docker stop smoke
